env:
   - TERM=dumb
language: java
matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: osx
  allow_failures:
    - jdk: openjdk7
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: ./gradlew build
script: ./gradlew build shadowJar proguard
branches:
  only:
    - master
    - stable